### ISSUE TITLE
RULETA_ETSIDI

### ISSUE THREAD

**Issue by Saul-Marcos** [aigora/starter-code#13]
Logo:
![LOGO](https://user-images.githubusercontent.com/80189018/118459019-99e68500-b6fb-11eb-810c-41dbd5c402fa.png)

Código en formato .txt:
[Codigo formato texto.txt](https://github.com/aigora/starter-code/files/6492435/Codigo.formato.texto.txt)

Ficheros:
[mesa.txt](https://github.com/aigora/starter-code/files/6492439/mesa.txt)
[tablero.txt](https://github.com/aigora/starter-code/files/6492442/tablero.txt)
[usuarios.txt](https://github.com/aigora/starter-code/files/6492445/usuarios.txt)

Readme:
[Readme.txt](https://github.com/aigora/starter-code/files/6492448/Readme.txt)

Tal y como se aprecia en las conversaciones adjuntas, mis compañeros de grupo han abandonado la asignatura, así que el proyecto lo he realizado yo solo. 
![image](https://user-images.githubusercontent.com/80189018/118460186-bdf69600-b6fc-11eb-9ac4-3fabbac880c6.png)
![image](https://user-images.githubusercontent.com/80189018/118460220-c5b63a80-b6fc-11eb-8382-a5ed6c362e1b.png)

**Comment by oscarperpinan** [comment]
@Saul-Marcos , éste no es el lugar para la entrega del trabajo. Ponte en contacto conmigo vía correo electrónico.
Elimino esta issue y los documentos asociados.
